### ISSUE TITLE
The meaning of different strategies

### ISSUE THREAD

**Issue by qxpBlog** [zhengzangw/Sequence-Scheduling#1]
@zhengzangw Sorry, can you explain the meanings of the following different strategies: seqsch、vanilla、gt、po?
![image](https://github.com/zhengzangw/Sequence-Scheduling/assets/96739096/4f5130fd-cd53-4dcb-ace6-b1e290b1a2ff)

**Comment by zhengzangw** [comment]
Sure. `seqsch` is our method. `vanilla` is to inference without our method. `gt` means using our method but with a ground truth knowledge of the text length, which serves as an upper bound of our method. These can also be found in our paper.

**Comment by qxpBlog** [comment]
> Sure. is our method. is to inference without our method. means using our method but with a ground truth knowledge of the text length, which serves as an upper bound of our method. These can also be found in our paper.`seqsch``vanilla``gt`

Thank you for your answer，I got it.
